### PR TITLE
Removal check of alert type

### PR DESCRIPTION
**Pull request by C-Lodder**
We provide documentation on which types are supported by default and if users extend the colour array, they should know what can and can't be added, so I'm removing this check.

### CODE REVIEW

**Comment by dgt41** [comment]
Actually, removing this check means that any string value is acceptable, which could lead in broken alerts (no styling at all). Why anyone will not use the already 5 defined values in their css to style them accordingly?

**Comment by C-Lodder** [comment]
Cause we're checking against the default values that WE provide. If the user extends the array of colours to add their own style, then the check is pointless cause.

We clearly state on the demo the type of alerts can that be used. If users decide to do something stupid like `<tk-alert type="crap"></tk-alert>` then that's their problem.

As I said before, we're providing a toolkit it's not up to us to ensure every scenario

**Comment by dgt41** [comment]
> If the user extends the array of colours to add their own style, then the check is pointless cause.

CSS should be always in sync with the js. So if js expects 5 different (given) strings then the css cannot have more or different named strings. We can't and shouldn't try to satisfy every possible scenario or we end up with crap bloated code. My 2c

**Comment by C-Lodder** [comment]
If that's the case, then if a user wants to add their own alert colour, for example:
```
$theme-colors: map-merge((
  grey: #333
), $theme-colors);
```

Then you're saying they need to also add `grey` to [here](https://github.com/toiletKit/custom-elements/pull/33/files#diff-5a5c5f76b5305bd7907be3091c725edeL62) and then recompile the JS?

Cmon, that's a little too much just to add your own style.

**Comment by dgt41** [comment]
> Then you're saying they need to also add grey to here and then recompile the JS?

YES!

**Comment by C-Lodder** [comment]
If I was using CE's, I'd personally hate to have to do that. I see absolutely no benefit of making the user recompile the JS just so they can check if they're adding the correct value to the `type` attribute

**Comment by dgt41** [comment]
@C-Lodder you need to understand what this check is doing:
if you remove it and try `el.setAttribute('type', 'idiotuser')` then you have a broken thing.
So all I'm saying is that i prefer a solid implementation over random features.

PS if you think this is crucial, then make the elements in the settings.json objects, pass any data there and then collect it in the scss and js files. Of course you still need to recompile, but that is the nature of modern javascript, so that shouldn't be a problem these days

**Comment by C-Lodder** [comment]
Yup, I know something like `el.setAttribute('type', 'idiotuser')` wouldn't work. Like I said, if we provide a list of default `type` values that are allowed in the docs, then clearly state that that they can add their own to the SCSS, then I still see no reason for the JS check.

I'm against adding silly sanity checks for users who dont follow docs

**Pull request closed without merging**
